baseURL: "https://themeflock.netlify.com/"
languageCode: "en-us"
title: "Chennai JS"
theme: "flock"
canonifyURLs: true
paginate: 2
pygmentsCodeFences: true
pygmentsUseClasses: true
pygmentsUseClassic: true


categories: [
  "HTML",
]
params:
  description: "Lean hugo theme for easy publishing"
  subtitle: "Lean hugo theme for easy publishing"

