version: '3'
services:
  flock:
    build:
      context: .
      dockerfile: Dockerfile
    command: hugo server -wvFD --bind=0.0.0.0
    volumes:
      - .:/usr/share/flock
    ports:
      - "1313:1313"
